version: '2.4'

services:
  main:
    container_name: demoimageclassification_gpu_main
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VNC_PASSWORD=secret
      - DISPLAY=:0
    ports:
      - 5900:5900
    volumes:
      - /dev/video0:/dev/video0
      - ../..:/app
    entrypoint: ./docker/gpu/entrypoint.sh
    command: ["python", "camera.py"]
    privileged: true
    runtime: nvidia # GPU enable
    tty: true
    stdin_open: true
